In [34]:
import duckdb
from dotenv import load_dotenv
import os
import s3fs
import polars as pl
import boto3
load_dotenv()

pl.Config.set_fmt_str_lengths(50)

polars.config.Config

In [26]:

s3 = s3fs.S3FileSystem(
    key=os.getenv("S3_ACCESS_KEY"),
    secret=os.getenv("S3_SECRET_KEY"),
    token=os.getenv("AWS_SESSION_TOKEN"),  # optional but important if using temp creds
    client_kwargs={
        "region_name": "ca-central-1"
    }
)

In [27]:
# s3 setup using boto3
s3_client = boto3.client(
    's3',
    aws_access_key_id=os.getenv("S3_ACCESS_KEY"),
    aws_secret_access_key=os.getenv("S3_SECRET_KEY"),
    aws_session_token=os.getenv("AWS_SESSION_TOKEN"),  # optional but important if using temp creds
    region_name='ca-central-1'
)

In [28]:
# scan s3 bucket using duckdb

con = duckdb.connect()

bucket = os.getenv("S3_BUCKET")

snp500 = con.execute(f"""
SELECT *
FROM read_csv_auto('s3://{bucket}/post-earnings-forecast/**/*.csv')

""").df()
snp500

       #                 Company Symbol Weight   Price   Chg   % Chg
0      1             NVIDIA Corp   NVDA  7.69%  215.33 -4.18  -1.90%
1      2               Apple Inc   AAPL  6.69%  308.82  3.83   1.26%
2      3          Microsoft Corp   MSFT  4.58%  418.57 -0.52  -0.12%
3      4          Amazon.com Inc   AMZN  4.22%  266.32 -2.14  -0.80%
4      5            Alphabet Inc  GOOGL  3.53%  382.97 -4.69  -1.21%
..   ...                     ...    ...    ...     ...   ...     ...
498  499               Pool Corp   POOL  0.01%  184.64  2.95   1.62%
499  500      Conagra Brands Inc    CAG  0.01%   13.56  0.18   1.35%
500  501  Campbell's Company/The    CPB  0.01%   20.58  0.53   2.64%
501  502               News Corp    NWS  0.01%   29.68 -0.40  -1.33%
502  503        EPAM Systems Inc   EPAM  0.01%  102.69 -0.50  -0.48%

[503 rows x 7 columns]

# Earnings

In [29]:
#  delta table for earnings
DELTA_EARNINGS = f"s3://{os.getenv('S3_BUCKET')}/post-earnings-forecast/earnings_delta/"


# storage options for delta lake
storage_options = {
    "AWS_ACCESS_KEY_ID": os.getenv("AWS_ACCESS_KEY_ID"),
    "AWS_SECRET_ACCESS_KEY": os.getenv("AWS_SECRET_ACCESS_KEY"),
    "AWS_REGION": "ca-central-1",
}


delta_earnings_df = pl.scan_delta(DELTA_EARNINGS, storage_options=storage_options).collect()
delta_earnings_df


delta_earnings_df

shape: (24_294, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ fiscalDat ┆ reportedD ┆ reportedE ┆ estimated ┆ … ┆ fiscal_mo ┆ fiscal_ye ┆ av_quarte ┆ time_fro │
│ eEnding   ┆ ate       ┆ PS        ┆ EPS       ┆   ┆ nth       ┆ ar        ┆ r         ┆ m        │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ date      ┆ date      ┆ str       ┆ str       ┆   ┆ i8        ┆ i32       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2015-09-3 ┆ 2015-11-0 ┆ 1.85      ┆ 1.85      ┆ … ┆ 9         ┆ 2015      ┆ 2015Q3    ┆ 20151106 │
│ 0         ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆           ┆ T0000    │
│ 2019-03-3 ┆ 2019-05-0 ┆ 2.26      ┆ 2.29      ┆ … ┆ 3         ┆ 2019      ┆ 2019Q1    ┆ 20190504 │
│ 1         ┆ 4         ┆           ┆           ┆   ┆           ┆           ┆           ┆ T0000    │
│ 2017-09-3 ┆ 2017-11-0 ┆ 1.4       ┆ 1.58      ┆ … ┆ 9         ┆ 2017      ┆ 2017Q3    ┆ 20171103 │
│ 0         ┆ 3         ┆           ┆           ┆   ┆           ┆           ┆           ┆ T0000    │
│ 2016-12-3 ┆ 2017-02-2 ┆ 1.78      ┆ 1.83      ┆ … ┆ 12        ┆ 2016      ┆ 2016Q4    ┆ 20170225 │
│ 1         ┆ 5         ┆           ┆           ┆   ┆           ┆           ┆           ┆ T0000    │
│ 2023-06-3 ┆ 2023-08-0 ┆ 4.62      ┆ 3.87      ┆ … ┆ 6         ┆ 2023      ┆ 2023Q2    ┆ 20230805 │
│ 0         ┆ 5         ┆           ┆           ┆   ┆           ┆           ┆           ┆ T0000    │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2014-09-3 ┆ 2014-10-2 ┆ 0.02      ┆ 0.02      ┆ … ┆ 9         ┆ 2014      ┆ 2014Q3    ┆ 20141022 │
│ 0         ┆ 2         ┆           ┆           ┆   ┆           ┆           ┆           ┆ T0000    │
│ 2025-09-3 ┆ 2025-11-0 ┆ 0.74      ┆ 0.63      ┆ … ┆ 9         ┆ 2025      ┆ 2025Q3    ┆ 20251105 │
│ 0         ┆ 5         ┆           ┆           ┆   ┆           ┆           ┆           ┆ T0000    │
│ 2025-03-3 ┆ 2025-05-0 ┆ 0.58      ┆ 0.53      ┆ … ┆ 3         ┆ 2025      ┆ 2025Q1    ┆ 20250507 │
│ 1         ┆ 7         ┆           ┆           ┆   ┆           ┆           ┆           ┆ T0000    │
│ 2024-09-3 ┆ 2024-11-0 ┆ 0.63      ┆ 0.52      ┆ … ┆ 9         ┆ 2024      ┆ 2024Q3    ┆ 20241107 │
│ 0         ┆ 7         ┆           ┆           ┆   ┆           ┆           ┆           ┆ T0000    │
│ 2016-06-3 ┆ 2016-07-2 ┆ 0.03      ┆ 0.03      ┆ … ┆ 6         ┆ 2016      ┆ 2016Q2    ┆ 20160728 │
│ 0         ┆ 8         ┆           ┆           ┆   ┆           ┆           ┆           ┆ T0000    │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [24]:
delta_earnings_df.filter(
    pl.col('symbol') == 'AAPL'
)

shape: (50, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ fiscalDat ┆ reportedD ┆ reportedE ┆ estimated ┆ … ┆ fiscal_mo ┆ fiscal_ye ┆ av_quarte ┆ time_fro │
│ eEnding   ┆ ate       ┆ PS        ┆ EPS       ┆   ┆ nth       ┆ ar        ┆ r         ┆ m        │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ date      ┆ date      ┆ str       ┆ str       ┆   ┆ i8        ┆ i32       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2020-09-3 ┆ 2020-10-2 ┆ 0.73      ┆ 0.7       ┆ … ┆ 9         ┆ 2020      ┆ 2020Q3    ┆ 20201029 │
│ 0         ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆ T0000    │
│ 2019-03-3 ┆ 2019-04-3 ┆ 0.62      ┆ 0.59      ┆ … ┆ 3         ┆ 2019      ┆ 2019Q1    ┆ 20190430 │
│ 1         ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆ T0000    │
│ 2017-09-3 ┆ 2017-11-0 ┆ 0.5175    ┆ 0.4675    ┆ … ┆ 9         ┆ 2017      ┆ 2017Q3    ┆ 20171102 │
│ 0         ┆ 2         ┆           ┆           ┆   ┆           ┆           ┆           ┆ T0000    │
│ 2016-12-3 ┆ 2017-01-3 ┆ 0.84      ┆ 0.8025    ┆ … ┆ 12        ┆ 2016      ┆ 2016Q4    ┆ 20170131 │
│ 1         ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆ T0000    │
│ 2015-09-3 ┆ 2015-10-2 ┆ 0.49      ┆ 0.47      ┆ … ┆ 9         ┆ 2015      ┆ 2015Q3    ┆ 20151027 │
│ 0         ┆ 7         ┆           ┆           ┆   ┆           ┆           ┆           ┆ T0000    │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2017-06-3 ┆ 2017-08-0 ┆ 0.4175    ┆ 0.3925    ┆ … ┆ 6         ┆ 2017      ┆ 2017Q2    ┆ 20170801 │
│ 0         ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆ T0000    │
│ 2016-09-3 ┆ 2016-10-2 ┆ 0.4175    ┆ 0.415     ┆ … ┆ 9         ┆ 2016      ┆ 2016Q3    ┆ 20161025 │
│ 0         ┆ 5         ┆           ┆           ┆   ┆           ┆           ┆           ┆ T0000    │
│ 2016-03-3 ┆ 2016-04-2 ┆ 0.475     ┆ 0.5       ┆ … ┆ 3         ┆ 2016      ┆ 2016Q1    ┆ 20160426 │
│ 1         ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆           ┆ T0000    │
│ 2023-12-3 ┆ 2024-02-0 ┆ 2.18      ┆ 2.11      ┆ … ┆ 12        ┆ 2023      ┆ 2023Q4    ┆ 20240201 │
│ 1         ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆ T0000    │
│ 2020-06-3 ┆ 2020-07-3 ┆ 0.65      ┆ 0.51      ┆ … ┆ 6         ┆ 2020      ┆ 2020Q2    ┆ 20200730 │
│ 0         ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆ T0000    │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [30]:
# total syms in earnings delta
delta_earnings_df.select(pl.col('symbol').n_unique())

shape: (1, 1)
┌────────┐
│ symbol │
│ ---    │
│ u32    │
╞════════╡
│ 503    │
└────────┘

# Transcripts

In [41]:
DELTA_TRANSCRIPTS = f"s3://{os.getenv('S3_BUCKET')}/post-earnings-forecast/transcripts_delta/"
# polars options 

df_tx = pl.scan_delta(DELTA_TRANSCRIPTS, storage_options=storage_options).collect()
df_tx.filter(pl.col('symbol') == 'NVDA').to_pandas().head()

,fiscalDateEnding,reportedDate,reportedEPS,estimatedEPS,surprise,surprisePercentage,reportTime,symbol,fiscal_month,fiscal_year,av_quarter,time_from,transcript
0,2014-10-31,2014-11-06,0.008,0.007,0.001,14.2857,post-market,AMP,6,2015,2015Q2,20150722T0000,"[{'speaker': 'Operator', 'title': 'Operator', ..."
1,2016-07-31,2016-08-11,0.01,0.009,0.001,11.1111,post-market,NVDA,7,2016,2016Q3,20160811T0000,"[{'speaker': 'Operator', 'title': 'Operator', ..."
2,2018-07-31,2018-08-16,0.049,0.044,0.005,11.3636,post-market,AMP,9,2018,2018Q3,20181023T0000,"[{'speaker': 'Operator', 'title': 'Operator', ..."
3,2018-10-31,2018-11-15,0.046,0.047,-0.001,-2.1277,post-market,AMP,12,2018,2018Q4,20190130T0000,"[{'speaker': 'Operator', 'title': 'Operator', ..."
4,2020-07-31,2020-08-19,0.055,0.049,0.006,12.2449,post-market,AMP,9,2020,2020Q3,20201028T0000,"[{'speaker': 'Operator', 'title': 'Operator', ..."

In [42]:
df_tx['symbol'].n_unique()

169

# OHLVC

In [45]:
DELTA_OHLVC = f"s3://{bucket}/post-earnings-forecast/ohlcv_delta/"
df = pl.read_delta(DELTA_OHLVC, storage_options=storage_options)
df.head()

shape: (5, 7)
┌────────┬────────┬────────┬────────┬────────┬────────┬────────┐
│ symbo… ┆ date   ┆ open   ┆ high   ┆ low    ┆ close  ┆ volum… │
│ ---    ┆ ---    ┆ ---    ┆ ---    ┆ ---    ┆ ---    ┆ ---    │
│ str    ┆ date   ┆ f64    ┆ f64    ┆ f64    ┆ f64    ┆ i64    │
╞════════╪════════╪════════╪════════╪════════╪════════╪════════╡
│ BRK-B  ┆ 2011-… ┆ 82.73… ┆ 83.23… ┆ 82.65… ┆ 83.02… ┆ 28178… │
│ BRK-B  ┆ 2013-… ┆ 101.4… ┆ 102.3… ┆ 101.3… ┆ 102.1… ┆ 88755… │
│ BRK-B  ┆ 2013-… ┆ 101.4… ┆ 102.2… ┆ 100.4… ┆ 102.0… ┆ 48128… │
│ BRK-B  ┆ 2013-… ┆ 103.2… ┆ 103.5… ┆ 102.7… ┆ 103.2… ┆ 33163… │
│ BRK-B  ┆ 2013-… ┆ 103.6… ┆ 103.7… ┆ 102.7… ┆ 102.7… ┆ 72538… │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┘

In [46]:
df['symbol'].n_unique()

503

In [47]:
df.shape

(4385666, 7)

In [63]:
# filter frame from 2010
df.filter(pl.col('date') >=  pl.lit("2010-01-01").str.to_date()).shape

(1954181, 7)