In [2]:
import polars as pl

In [3]:
# ── Tech modeling table ───────────────────────────────────────────────────
tech_path = "../data/model_staging/tech_modeling_table.parquet"
df_tech   = pl.read_parquet(tech_path)
print(f"Tech table shape: {df_tech.shape}")

Tech table shape: (24048, 239)

In [26]:
df_tech.head(5)

shape: (5, 239)
┌────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ symbol ┆ earnings_d ┆ entry_pric ┆ target_re ┆ … ┆ sigma_t+1 ┆ obv_zscor ┆ vwap_pct_ ┆ vix_close │
│ ---    ┆ ate        ┆ e          ┆ turn      ┆   ┆ ---       ┆ e_t+1     ┆ t+1       ┆ _t+1      │
│ str    ┆ ---        ┆ ---        ┆ ---       ┆   ┆ f64       ┆ ---       ┆ ---       ┆ ---       │
│        ┆ date       ┆ f64        ┆ f64       ┆   ┆           ┆ f64       ┆ f64       ┆ f64       │
╞════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ CTSH   ┆ 2019-05-02 ┆ 52.934376  ┆ 0.015865  ┆ … ┆ 0.034663  ┆ -2.755382 ┆ -0.115085 ┆ 12.87     │
│ CTSH   ┆ 2023-05-03 ┆ 59.368004  ┆ 0.016704  ┆ … ┆ 0.019947  ┆ 0.725313  ┆ 0.044019  ┆ 20.09     │
│ CTSH   ┆ 2024-02-06 ┆ 74.632195  ┆ 0.008462  ┆ … ┆ 0.009355  ┆ 1.911262  ┆ 0.011745  ┆ 12.83     │
│ CTSH   ┆ 2022-07-27 ┆ 62.314026  ┆ 0.042795  ┆ … ┆ 0.021318  ┆ -0.164584 ┆ -0.003839 ┆ 22.33     │
│ CTSH   ┆ 2019-07-31 ┆ 59.529625  ┆ -0.014004 ┆ … ┆ 0.008696  ┆ 1.447868  ┆ 0.015066  ┆ 17.870001 │
└────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [4]:
# read the parquet file into a polars dataframe
df_ohlcv = pl.read_parquet("../ingestion/data/backup/ohlcv_delta_backup.parquet")

df_ohlcv.head(5)

shape: (5, 7)
┌────────┬────────────┬────────────┬────────────┬────────────┬────────────┬─────────┐
│ symbol ┆ date       ┆ open       ┆ high       ┆ low        ┆ close      ┆ volume  │
│ ---    ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---     │
│ str    ┆ date       ┆ f64        ┆ f64        ┆ f64        ┆ f64        ┆ i64     │
╞════════╪════════════╪════════════╪════════════╪════════════╪════════════╪═════════╡
│ BRK-B  ┆ 2011-01-27 ┆ 82.739998  ┆ 83.239998  ┆ 82.650002  ┆ 83.029999  ┆ 2817800 │
│ BRK-B  ┆ 2013-02-28 ┆ 101.440002 ┆ 102.330002 ┆ 101.309998 ┆ 102.160004 ┆ 8875500 │
│ BRK-B  ┆ 2013-03-01 ┆ 101.449997 ┆ 102.25     ┆ 100.440002 ┆ 102.050003 ┆ 4812800 │
│ BRK-B  ┆ 2013-03-06 ┆ 103.290001 ┆ 103.559998 ┆ 102.760002 ┆ 103.239998 ┆ 3316300 │
│ BRK-B  ┆ 2013-03-15 ┆ 103.669998 ┆ 103.790001 ┆ 102.790001 ┆ 102.790001 ┆ 7253800 │
└────────┴────────────┴────────────┴────────────┴────────────┴────────────┴─────────┘

In [5]:
df_tech = df_tech.join(df_ohlcv, left_on=["symbol", "earnings_date"], right_on=["symbol", "date"], how="left")

In [12]:
df_tech.filter(pl.col('symbol') == 'NVDA').sort('earnings_date', descending=True)

shape: (49, 245)
┌────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ symbol ┆ earnings_d ┆ entry_pric ┆ target_re ┆ … ┆ low       ┆ close     ┆ volume    ┆ close_t1  │
│ ---    ┆ ate        ┆ e          ┆ turn      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str    ┆ ---        ┆ ---        ┆ ---       ┆   ┆ f64       ┆ f64       ┆ i64       ┆ f64       │
│        ┆ date       ┆ f64        ┆ f64       ┆   ┆           ┆           ┆           ┆           │
╞════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ NVDA   ┆ 2026-02-25 ┆ 184.87999  ┆ 0.01482   ┆ … ┆ 193.7795  ┆ 195.54940 ┆ 250637100 ┆ 184.87999 │
│        ┆            ┆            ┆           ┆   ┆           ┆ 8         ┆           ┆           │
│ NVDA   ┆ 2025-11-19 ┆ 180.620163 ┆ 0.02779   ┆ … ┆ 182.80991 ┆ 186.49951 ┆ 247246400 ┆ 180.62016 │
│        ┆            ┆            ┆           ┆   ┆ 5         ┆ 2         ┆           ┆ 3         │
│ NVDA   ┆ 2025-08-27 ┆ 180.14006  ┆ 0.000667  ┆ … ┆ 179.07024 ┆ 181.56982 ┆ 235518900 ┆ 180.14006 │
│        ┆            ┆            ┆           ┆   ┆           ┆ 4         ┆           ┆           │
│ NVDA   ┆ 2025-05-28 ┆ 139.157211 ┆ 0.041742  ┆ … ┆ 134.75824 ┆ 134.77824 ┆ 304021100 ┆ 139.15721 │
│        ┆            ┆            ┆           ┆   ┆ 4         ┆ 4         ┆           ┆ 1         │
│ NVDA   ┆ 2025-02-26 ┆ 120.110649 ┆ 0.041115  ┆ … ┆ 128.44792 ┆ 131.237   ┆ 322553800 ┆ 120.11064 │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆ 9         │
│ …      ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ NVDA   ┆ 2015-02-11 ┆ 0.535051   ┆ 0.00852   ┆ … ┆ 0.495942  ┆ 0.499301  ┆ 320832000 ┆ 0.535051  │
│ NVDA   ┆ 2014-11-06 ┆ 0.472827   ┆ 0.033156  ┆ … ┆ 0.474499  ┆ 0.4831    ┆ 394088000 ┆ 0.472827  │
│ NVDA   ┆ 2014-08-07 ┆ 0.451952   ┆ 0.02927   ┆ … ┆ 0.412466  ┆ 0.415321  ┆ 407696000 ┆ 0.451952  │
│ NVDA   ┆ 2014-05-06 ┆ 0.432596   ┆ 0.028462  ┆ … ┆ 0.430938  ┆ 0.432122  ┆ 416188000 ┆ 0.432596  │
│ NVDA   ┆ 2014-02-12 ┆ 0.409201   ┆ 0.098255  ┆ … ┆ 0.384215  ┆ 0.396708  ┆ 744528000 ┆ 0.409201  │
└────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [15]:
df_tech.filter(pl.col('symbol') == 'NVDA').sort('earnings_date', descending=True).select([
    pl.col("symbol"),
    pl.col("earnings_date"),
    pl.col("close"),
    #pl.col("^ema.*$"),
    pl.col("ema50_pct_t0"),
    pl.col("ema200_pct_t0")
])

shape: (49, 5)
┌────────┬───────────────┬────────────┬──────────────┬───────────────┐
│ symbol ┆ earnings_date ┆ close      ┆ ema50_pct_t0 ┆ ema200_pct_t0 │
│ ---    ┆ ---           ┆ ---        ┆ ---          ┆ ---           │
│ str    ┆ date          ┆ f64        ┆ f64          ┆ f64           │
╞════════╪═══════════════╪════════════╪══════════════╪═══════════════╡
│ NVDA   ┆ 2026-02-25    ┆ 195.549408 ┆ 0.049807     ┆ 0.13462       │
│ NVDA   ┆ 2025-11-19    ┆ 186.499512 ┆ 0.001128     ┆ 0.159697      │
│ NVDA   ┆ 2025-08-27    ┆ 181.569824 ┆ 0.078171     ┆ 0.286934      │
│ NVDA   ┆ 2025-05-28    ┆ 134.778244 ┆ 0.114309     ┆ 0.13115       │
│ NVDA   ┆ 2025-02-26    ┆ 131.237    ┆ -0.017838    ┆ 0.078695      │
│ …      ┆ …             ┆ …          ┆ …            ┆ …             │
│ NVDA   ┆ 2015-02-11    ┆ 0.499301   ┆ 0.038624     ┆ 0.095374      │
│ NVDA   ┆ 2014-11-06    ┆ 0.4831     ┆ 0.081663     ┆ 0.122673      │
│ NVDA   ┆ 2014-08-07    ┆ 0.415321   ┆ -0.049883    ┆ 0.003262      │
│ NVDA   ┆ 2014-05-06    ┆ 0.432122   ┆ 0.002928     ┆ 0.111261      │
│ NVDA   ┆ 2014-02-12    ┆ 0.396708   ┆ 0.070053     ┆ 0.125392      │
└────────┴───────────────┴────────────┴──────────────┴───────────────┘